import type { Overview, TestCase } from "./types";

// 后端未起时的展示用 demo 数据（对标设计稿）。后端 REST 就绪后前端自动连真实数据。
export const mockCases: TestCase[] = [
  {
    id: "tc_search_summarize",
    name: "Search then summarize",
    user_message: "Find recent MCP testing guidance, then summarize the key recommendations.",
    expected_tools: ["search", "summarize"],
    expectations: [
      { kind: "tool_call_order", tools: ["search", "summarize"] },
      { kind: "expected_tools", tools: ["search", "summarize"] },
      { kind: "text_contains", needle: "recommendations" },
    ],
    mock: {
      search: { hits: [{ title: "MCP eval guide", url: "https://example.com" }], total: 1 },
      summarize: "Key recommendations for MCP testing.",
    },
    tags: ["core", "tool-flow"],
    judge_mode: "rule",
    last_result: "passed",
    updated_ago: "4m ago",
  },
  {
    id: "tc_proxy_timeout",
    name: "Proxy timeout fallback",
    user_message: "Call a slow backend tool.",
    expected_tools: ["fs__read"],
    expectations: [{ kind: "expected_tools", tools: ["fs__read"] }],
    mock: { "fs__read": "file-content" },
    tags: ["proxy", "resilience"],
    judge_mode: "rule",
    last_result: "failed",
    updated_ago: "1h ago",
  },
  {
    id: "tc_mock_equiv",
    name: "Mock equivalence match",
    user_message: "search for ABC",
    expected_tools: ["search"],
    expectations: [{ kind: "expected_tools", tools: ["search"] }],
    mock: { search: { hits: [], total: 0 } },
    tags: ["mock"],
    judge_mode: "rule",
    last_result: "passed",
    updated_ago: "Yesterday",
  },
  {
    id: "tc_judge_order",
    name: "Judge tool call order",
    user_message: "multi-step flow",
    expected_tools: ["a", "b", "c"],
    expectations: [{ kind: "tool_call_order", tools: ["a", "b", "c"] }],
    mock: { a: "1", b: "2", c: "3" },
    tags: ["judge"],
    judge_mode: "rule",
    last_result: "review",
    updated_ago: "2d ago",
  },
  {
    id: "tc_ai_rubric",
    name: "AI rubric judgement",
    user_message: "polite refusal path",
    expected_tools: [],
    expectations: [],
    mock: {},
    rubric: "agent refuses politely without hallucinating",
    tags: ["ai"],
    judge_mode: "ai",
    last_result: "draft",
    updated_ago: "3d ago",
  },
];

export const mockOverview: Overview = {
  total_cases: 42,
  pass_rate: 91.7,
  median_run: "6.4s",
  changed_tools: 3,
  passed: 22,
  failed: 2,
  skipped: 3,
  coverage_done: 24,
  coverage_total: 27,
  recent_runs: [
    { id: "AR-184", commit: "9d2e7f1", scope: "Changed cases ·12", passed: 11, failed: 1, total: 12, duration: "28.4s", when: "4m ago" },
    { id: "AR-183", commit: "3fc804a", scope: "Full suite ·42", passed: 39, failed: 3, total: 42, duration: "2m 18s", when: "1h ago" },
    { id: "AR-182", commit: "3fc804a", scope: "Changed cases ·8", passed: 8, failed: 0, total: 8, duration: "18.2s", when: "3h ago" },
    { id: "AR-181", commit: "b27c190", scope: "Tool contract ·16", passed: 15, failed: 1, total: 16, duration: "44.7s", when: "Yesterday" },
    { id: "AR-180", commit: "b27c190", scope: "Full suite ·40", passed: 40, failed: 0, total: 40, duration: "2m 06s", when: "Yesterday" },
  ],
  suite_growth: [
    { name: "tc_proxy_timeout", delta: 2, when: "4m ago" },
    { name: "tc_mock_equiv", delta: 1, when: "1h ago" },
    { name: "tc_judge_order", delta: 2, when: "3h ago" },
    { name: "tc_sqlite_restart", delta: 1, when: "Yesterday" },
    { name: "tc_transport_done", delta: 3, when: "Yesterday" },
  ],
};
